server:
  port: 9411
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.31.90:10574
      username: username
      password: password
  storage:
    # 存储类型 mem\mysql\elasticsearch
    type: mysql
    mysql:
      jdbc-url:
      host: localhost
      port: 3306
      username: username
      password: password
      db: zipkin
      max-active: 10
      use-ssl: false